export const books = [             // books
   { id: 1,
   img: 'https://content1.rozetka.com.ua/goods/images/big_tile/11759163.jpg',
   bookName: 'Перша книга малюка',
   title: 'Шеррі Даскі Рінкер та Том Ліхтенгелд',
   price: '12$',
   },
   { id: 2,
   bookName: "Доісторичні тварини",
   title: "Гуменна Л.М.",
   img: 'https://content.rozetka.com.ua/goods/images/big_tile/114625179.jpg',
   price: '5$',
   },
   { id: 3,
   bookName: "Міні Віммельбух",
   title: "Ізабель Гьонтген.",
   img: 'https://content.rozetka.com.ua/goods/images/big_tile/28380795.jpg',
   price: '10$',
   },
];